name: Zephyr Build

on:
  push:
    branches: [ main ]
    paths:
      - 'firmware/**'
      - '.github/workflows/build.yaml'
  pull_request:
    branches: [ main ]
    paths:
      - 'firmware/**'
      - '.github/workflows/build.yaml'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zephyrprojectrtos/zephyr-build:v0.29.0
      options: --user root

    env:
      ZEPHYR_SDK_INSTALL_DIR: /opt/toolchains/zephyr-sdk-1.0.0

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          path: my-project

      - name: Cache Zephyr Workspace
        id: cache-zephyr
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
        with:
          path: |
            my-project/.west
            my-project/bootloader
            my-project/modules
            my-project/tools
            my-project/zephyr
          key: ${{ runner.os }}-zephyr-${{ hashFiles('my-project/firmware/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-zephyr-

      - name: Initialize West
        run: |
          cd my-project

          if [ ! -d ".west" ]; then
            west init -l firmware
          fi
          
          west update

      - name: Build Application
        run: |
          cd my-project
          west build -b native_sim firmware/app

      - name: Run Tests Tagged with "cloudsense"
        run: |
          cd my-project
          west twister -p native_sim -T firmware -t cloudsense --outdir test-results -v
